branches:
  only:
    - master

environment:
  nodejs_version: "6"

install:
  - choco install googlechrome --ignore-checksums
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

# Don't actually build.
build: off
